FROM registry.access.redhat.com/hi/python:3.12-fips-builder AS deps
USER root
RUN mkdir -p /install && pip install flask --prefix=/install

FROM registry.access.redhat.com/hi/python:3.12-fips
COPY --from=deps /install /usr/local
COPY app.py /app/app.py
WORKDIR /app
EXPOSE 8080
ENV RHHI_VARIANT=fips
# Appropriately set the stop signal for the python interpreter executed as PID 1
STOPSIGNAL SIGINT
CMD ["python3", "app.py"]
